In [1]:
import numpy as np

In [2]:
ls = [1,2,3,4]
a1 = np.array(ls)


In [3]:
print(a1)

[1 2 3 4]


In [4]:
a1.shape

(4,)

In [5]:
a1

array([1, 2, 3, 4])

In [6]:
a1.dtype

dtype('int32')

In [7]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [8]:
np.__all__

['add_newdocs',
 'ModuleDeprecationWarning',
 'VisibleDeprecationWarning',
 '__version__',
 'pkgload',
 'PackageLoader',
 'show_config',
 'char',
 'rec',
 'memmap',
 'newaxis',
 'ndarray',
 'flatiter',
 'nditer',
 'nested_iters',
 'ufunc',
 'arange',
 'array',
 'zeros',
 'count_nonzero',
 'empty',
 'broadcast',
 'dtype',
 'fromstring',
 'fromfile',
 'frombuffer',
 'int_asbuffer',
 'where',
 'argwhere',
 'copyto',
 'concatenate',
 'fastCopyAndTranspose',
 'lexsort',
 'set_numeric_ops',
 'can_cast',
 'promote_types',
 'min_scalar_type',
 'result_type',
 'asarray',
 'asanyarray',
 'ascontiguousarray',
 'asfortranarray',
 'isfortran',
 'empty_like',
 'zeros_like',
 'ones_like',
 'correlate',
 'convolve',
 'inner',
 'dot',
 'outer',
 'vdot',
 'alterdot',
 'restoredot',
 'roll',
 'rollaxis',
 'moveaxis',
 'cross',
 'tensordot',
 'array2string',
 'get_printoptions',
 'set_printoptions',
 'array_repr',
 'array_str',
 'set_string_function',
 'little_endian',
 'require',
 'fromiter',
 'array_equ

In [9]:
def func_constant(values):
    print(values[0])


In [10]:
lst = [1,2,3]
func_constant(lst)


1


In [11]:
def func_linear(values):
    for val in values:
        print(val)

In [12]:
func_linear(lst)

1
2
3


In [13]:
def func_quadratic(lst):
    for val in lst:
        for val2 in lst:
            print("("+str(val)+", "+str(val2)+")")


In [14]:
func_quadratic(lst)

(1, 1)
(1, 2)
(1, 3)
(2, 1)
(2, 2)
(2, 3)
(3, 1)
(3, 2)
(3, 3)


In [15]:
def print_once(lst):
    for val in lst:
        print(val)

In [16]:
print_once(lst)

1
2
3


In [17]:
def print_two(lst):
    for val in lst:
        print(val)
    for val in lst:
        print(val)
    

In [18]:
print_two(lst)

1
2
3
1
2
3


In [19]:
import ctypes

In [28]:
class DA(object):
    def __init__(self):
        self.n = 0
        self.cap = 1
        self.A = self.make_array(self.cap)
    def __len__(self):
        return self.n
    def __getitem__(self,k):
        if not 0 <= k < self.n:
            raise IndexError('Index is out of range.')
            return None
        
        return self.A[k]
    def append(self, ele):
        if self.n == self.cap:
            self._resize(2*self.cap)
        self.A[self.n] = ele
        self.n +=13.
    def _resize(self, new_cap):
        B = self.make_array(new_cap)
        for k in range(self.n):
            B[k] = self.A[k]
        self.A = B
        self.cap = new_cap
    def make_array(self,new_cap):
        return (new_cap * ctypes.py_object)()


In [29]:
arr = DA()

In [30]:
arr.append(1)

In [31]:
len(arr)

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
arr.append(2)

TypeError: indices must be integer

In [25]:
len(arr)

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
arr[1]

IndexError: invalid index

In [27]:
print(arr)

In [40]:
class stack(object):
    #__init__ cannot be a lambda function
    def __init__(self):
        self.items = []
    isEmpty = lambda self: self.items == []
    push = lambda self, item: self.items.append(item)        
    pop = lambda self: self.items.pop()
    peek = lambda self: self.items[-1]
    size = lambda self: len(self.items)
    __str__ = lambda self: str(self.items)

In [41]:
st = stack()

In [42]:
st.push(1)

In [43]:
st.push(2)
st.push(3)
st.push(4)
st.push(5)

In [44]:
print(st)

[1, 2, 3, 4, 5]


In [45]:
st.size()

5

In [46]:
st.isEmpty()

False

In [47]:
st.peek()

5

In [48]:
st.size()

5

In [49]:
class Q(object):
    def __init__(self):
        self.items = []
    isEmpty = lambda self: self.items == []
    enqueue = lambda self, item: self.items.insert(0, item)
    dequeue = lambda self: self.items.pop()
    def size(self):
        return len(self.items)

In [50]:
q = Q()
q.size()

0

In [51]:
q.isEmpty()

True

In [52]:
q.enqueue("Hello")

In [37]:
q.isEmpty()

False

In [38]:
q.size()

1

In [39]:
q.dequeue()

'Hello'

In [9]:
q.size()

0

In [10]:
q.isEmpty()

True

In [1]:
class Deque:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def addFront(self, item):
        self.items.append(item)

    def addRear(self, item):
        self.items.insert(0,item)

    def removeFront(self):
        return self.items.pop()

    def removeRear(self):
        return self.items.pop(0)

    def size(self):
        return len(self.items)

In [2]:
d = Deque()
d.addFront("asdu")